[build-system]
requires = ["setuptools >= 40.6.0", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "NitrogenDeposition-CMIP7"
version = "0.0"
requires-python = ">=3.7"

[tool.setuptools]
packages = ["nitrogendeposition"]
