channels:
  - conda-forge
  - coecms
  - nodefaults
dependencies:
  - black
  - cftime=1.0.4.2
  - dask=2.9.2
  - esmf
  - esmpy
  - f90nml
  - filelock
  - flake8
  - gdal=2.4.1
  - iris=2.3
  - isort<5.12
  - mo_pack
  - mule
  - numba
  - numpy=1.17.5
  - pre-commit
  - pykdtree
  - python=3.7.6
  - pyflakes=2.1.1
  - pytest
  - python-stratify
  - sphinx
  - sphinx_rtd_theme
  - sphinx-argparse
